// Copyright 2016 - 2024 The excelize Authors. All rights reserved. Use of
// this source code is governed by a BSD-style license that can be found in
// the LICENSE file.
//
// Package excelize providing a set of functions that allow you to write to and
// read from XLAM / XLSM / XLSX / XLTM / XLTX files. Supports reading and
// writing spreadsheet documents generated by Microsoft Excel™ 2007 and later.
// Supports complex components by high compatibility, and provided streaming
// API for generating or reading data from a worksheet with huge amounts of
// data. This library needs Go version 1.18 or later.
package excelize

import (
	"archive/zip"
	"bytes"
	"fmt"
	"io"
	"os"
)

// File defines the populated XLSX file struct.
type File struct {
	oxmlFileMap      map[string][]byte
	sheetMap         map[string]string
	WorkBook         *xlsxWorkbook
	sheets           map[string]*xlsxWorksheet
	Path             string
	Styles           *xlsxStyleSheet
	Theme            *xlsxTheme
	DecodeVMLDrawing map[string]*decodeVmlDrawing
	VMLDrawing       map[string]*vmlDrawing
	Drawings         map[string]*xlsxWsDr
	Comments         map[string]*xlsxComments
	SharedStrings    *xlsxSST
	CalcChain        *xlsxCalcChain
	UnsupportedTypes map[string][]byte
	options          *Options
	zip              *zip.ReadCloser
}

// Options defines the options for opening and reading the spreadsheet.
type Options struct {
	Password          string
	RawCellValue      bool
	UnzipSizeLimit    int64
	UnzipXMLSizeLimit int64
	ShortDatePattern  string
	LongDatePattern   string
	LongTimePattern   string
	CultureInfo       CultureName
}

// CultureName is the type for locale-specific settings.
type CultureName byte

const (
	CultureNameUnknown CultureName = iota
	CultureNameEnUS
	CultureNameZhCN
	CultureNameZhTW
)

// NewFile provides a function to create a new file by default template.
// The newly created workbook will contain a default worksheet named "Sheet1".
// For example:
//
//	f := excelize.NewFile()
func NewFile(opts ...Options) *File {
	f := newFile()
	f.options = parseOptions(opts...)
	f.WorkBook = &xlsxWorkbook{}
	f.newSheet("Sheet1")
	return f
}

// newFile is a helper that allocates and initializes a File struct.
func newFile() *File {
	return &File{
		oxmlFileMap:      make(map[string][]byte),
		sheetMap:         make(map[string]string),
		sheets:           make(map[string]*xlsxWorksheet),
		DecodeVMLDrawing: make(map[string]*decodeVmlDrawing),
		VMLDrawing:       make(map[string]*vmlDrawing),
		Drawings:         make(map[string]*xlsxWsDr),
		Comments:         make(map[string]*xlsxComments),
		UnsupportedTypes: make(map[string][]byte),
	}
}

// parseOptions normalizes options, returning the first provided or defaults.
func parseOptions(opts ...Options) *Options {
	if len(opts) > 0 {
		o := opts[0]
		return &o
	}
	return &Options{}
}

// OpenFile takes the name of a spreadsheet file and returns a populated
// spreadsheet file struct for it. For example, open a spreadsheet with
// password protection:
//
//	f, err := excelize.OpenFile("Book1.xlsx", excelize.Options{Password: "password"})
//	if err != nil {
//	    return
//	}
//	defer func() {
//	    if err := f.Close(); err != nil {
//	        fmt.Println(err)
//	    }
//	}()
func OpenFile(filename string, opts ...Options) (*File, error) {
	file, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer file.Close()
	info, err := file.Stat()
	if err != nil {
		return nil, err
	}
	f, err := OpenReader(file, opts...)
	if err != nil {
		return nil, err
	}
	f.Path = filename
	_ = info
	return f, nil
}

// OpenReader reads data streams from io.Reader and returns a populated
// spreadsheet file.
func OpenReader(r io.Reader, opts ...Options) (*File, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}
	zr, err := zip.NewReader(bytes.NewReader(b), int64(len(b)))
	if err != nil {
		return nil, fmt.Errorf("excelize: %w", err)
	}
	f := newFile()
	f.options = parseOptions(opts...)
	if err = f.readZip(zr); err != nil {
		return nil, err
	}
	return f, nil
}

// readZip reads the contents of a zip archive into the file struct.
func (f *File) readZip(zr *zip.Reader) error {
	for _, v := range zr.File {
		rc, err := v.Open()
		if err != nil {
			return err
		}
		content, err := io.ReadAll(rc)
		rc.Close()
		if err != nil {
			return err
		}
		f.oxmlFileMap[v.Name] = content
	}
	return nil
}

// Close closes and cleans up the open temporary file for the spreadsheet.
func (f *File) Close() error {
	if f.zip != nil {
		return f.zip.Close()
	}
	return nil
}
