// Copyright 2016 - 2024 The excelize Authors. All rights reserved. Use of
// this source code is governed by a BSD-style license that can be found in
// the LICENSE file.
//
// Package excelize providing a set of functions that allow you to write to and
// read from XLAM / XLSM / XLSX / XLTM / XLTX files. Supports reading and
// writing spreadsheet documents generated by Microsoft Excel™ 2007 and later.
// Supports complex components by high compatibility, and provided streaming
// API for generating or reading data from a worksheet with huge amounts of
// data. This library needs Go version 1.18 or later.
package excelize

import (
	"archive/zip"
	"bytes"
	"fmt"
	"io"
	"os"
)

// File defines the populated XLSX file struct.
type File struct {
	oxmlFileMap      map[string][]byte
	sheetMap         map[string]string
	WorkBook         *xlsxWorkbook
	sheets           map[string]*xlsxWorksheet
	Path             string
	Styles           *xlsxStyleSheet
	Theme            *xlsxTheme
	DecodeVMLDrawing map[string]*decodeVmlDrawing
	VMLDrawing       map[string]*vmlDrawing
	Drawings         map[string]*xlsxWsDr
	Comments         map[string]*xlsxComments
	SharedStrings    *xlsxSST
	CalcChain        *xlsxCalcChain
	UnsupportedTypes map[string][]byte
	options          *Options
	zip              *zip.ReadCloser
}

// Options defines the options for opening and reading the spreadsheet.
type Options struct {
	Password          string
	RawCellValue      bool
	UnzipSizeLimit    int64
	UnzipXMLSizeLimit int64
	ShortDatePattern  string
	LongDatePattern   string
	LongTimePattern   string
	CultureInfo       CultureName
}

// CultureName is the type for locale-specific settings.
type CultureName byte

const (
	CultureNameUnknown CultureName = iota
	CultureNameEnUS
	CultureNameZhCN
	CultureNameZhTW
)

// defaultSheetName is the name given to the first worksheet in a new workbook.
// Personal preference: using "Sheet1" matches Excel's default behavior and
// keeps things predictable when sharing files with other users.
const defaultSheetName = "Sheet1"

// NewFile provides a function to create a new file by default template.
// The newly created workbook will contain a default worksheet named "Sheet1".
// For example:
//
//	f := excelize.NewFile()
func NewFile(opts ...Options) *File {
	f := newFile()
	f.options = parseOptions(opts...)
	f.WorkBook = &xlsxWorkbook{}
	f.newSheet(defaultSheetName)
	return f
}

// newFile is a helper that allocates and initializes a File struct.
func newFile() *File {
	return &File{
		oxmlFileMap:      make(map[string][]byte),
		sheetMap:         make(map[string]string),
		sheets:           make(map[string]*xlsxWorksheet),
		DecodeVMLDrawing: make(map[string]*decodeVmlDrawing),
		VMLDrawing:       make(map[string]*vmlDrawing),
		Drawings:         make(map[string]*xlsxWsDr),
		Comments:         make(map[string]*xlsxComments),
		UnsupportedTypes: make(map[string][]byte),
	}
}

// parseOptions normalizes options, returning the first provided or defa
